app:
  mode: "debug"
  address: "127.0.0.1"
  port: 8081
  baseURL: "/aichat"
log:
  output: "cmd" # file or cmd
  level: "debug"
  filename: "app.log"
  max_size: 500
  max_age: 30
  max_backups: 7
mysql:
  dsn: "root:123456@tcp(127.0.0.1:3306)/demo?charset=utf8mb4&parseTime=True&loc=Local"
  # 最大连接数，即连接池大小
  max_open_conns: 100
  # 最大空闲连接数
  max_idle_conns: 10
redis:
  # host:port address.
  address: "127.0.0.1:6379"
  password: ""
  # Database to be selected after connecting to the server.
  db: 0
  # Maximum number of socket connections.
  # Default is 10 connections per every available CPU as reported by runtime.GOMAXPROCS.
  # 连接池大小，即最大连接数
  pool_size: 100
  # Maximum number of idle connections.
  # 最大空闲连接数
  min_idle_conns: 10